image: Visual Studio 2017

platform:
  - x64
  - x86


install:
- cinst autohotkey.install

build_script:
  cmd: choco pack

test_script:
  cmd: C:\Python36\python test.py

deploy_script:
  cmd: choco push

after_test:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
